### ISSUE TITLE
2.2.0 Release plan

### ISSUE THREAD

**Issue by sralloza** [sralloza/flask-web#28]
Fix:
* [x] Migrate to Github-Flow from Git-Flow (#34)
* [ ] Improve docs (#29)
* [ ] Include footer with contact info (#42)
* [ ] Use always CSS template (#41)
* [x] Change parser data identification (#27)
* [x] Set normal URL after forcing update of menus (#26)
* [x] Figure out how to fetch all menus' urls (#25)
   * [x] Add CLI option to process all urls or some of them with server offline (#30)
* [x] Add URL to show version (#24)
* [x] Improve logging (#15)
* [x] Use flask notifications (#31)
* [x] Improve testing (#32)
